# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 350)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.et_number = QtWidgets.QLabel(self.centralwidget)
        self.et_number.setGeometry(QtCore.QRect(0, 0, 400, 70))
        font = QtGui.QFont()
        font.setFamily("Tempus Sans ITC")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.et_number.setFont(font)
        self.et_number.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.et_number.setObjectName("et_number")
        self.btn0 = QtWidgets.QPushButton(self.centralwidget)
        self.btn0.setGeometry(QtCore.QRect(0, 280, 150, 70))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.btn0.setFont(font)
        self.btn0.setStyleSheet("background-color: rgb(87, 255, 171);\n"
"color: rgb(255, 255, 255);")
        self.btn0.setObjectName("btn0")
        self.btn_equal = QtWidgets.QPushButton(self.centralwidget)
        self.btn_equal.setGeometry(QtCore.QRect(150, 280, 150, 70))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.btn_equal.setFont(font)
        self.btn_equal.setStyleSheet("\n"
"background-color: rgb(0, 170, 0);\n"
"color: rgb(255, 255, 255);")
        self.btn_equal.setObjectName("btn_equal")
        self.btn1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn1.setGeometry(QtCore.QRect(0, 210, 100, 70))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.btn1.setFont(font)
        self.btn1.setStyleSheet("background-color: rgb(87, 255, 171);\n"
"color: rgb(255, 255, 255);")
        self.btn1.setObjectName("btn1")
        self.btn2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn2.setGeometry(QtCore.QRect(100, 210, 100, 70))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.btn2.setFont(font)
        self.btn2.setStyleSheet("background-color: rgb(87, 255, 171);\n"
"color: rgb(255, 255, 255);")
        self.btn2.setObjectName("btn2")
        self.btn3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn3.setGeometry(QtCore.QRect(200, 210, 100, 70))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.btn3.setFont(font)
        self.btn3.setStyleSheet("background-color: rgb(87, 255, 171);\n"
"color: rgb(255, 255, 255);")
        self.btn3.setObjectName("btn3")
        self.btn6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn6.setGeometry(QtCore.QRect(200, 140, 100, 70))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.btn6.setFont(font)
        self.btn6.setStyleSheet("background-color: rgb(87, 255, 171);\n"
"color: rgb(255, 255, 255);")
        self.btn6.setObjectName("btn6")
        self.btn4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn4.setGeometry(QtCore.QRect(0, 140, 100, 70))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.btn4.setFont(font)
        self.btn4.setStyleSheet("background-color: rgb(87, 255, 171);\n"
"color: rgb(255, 255, 255);")
        self.btn4.setObjectName("btn4")
        self.btn5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn5.setGeometry(QtCore.QRect(100, 140, 100, 70))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.btn5.setFont(font)
        self.btn5.setStyleSheet("background-color: rgb(87, 255, 171);\n"
"color: rgb(255, 255, 255);")
        self.btn5.setObjectName("btn5")
        self.btn8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn8.setGeometry(QtCore.QRect(100, 70, 100, 70))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.btn8.setFont(font)
        self.btn8.setStyleSheet("background-color: rgb(87, 255, 171);\n"
"color: rgb(255, 255, 255);")
        self.btn8.setObjectName("btn8")
        self.btn7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn7.setGeometry(QtCore.QRect(0, 70, 100, 70))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.btn7.setFont(font)
        self.btn7.setStyleSheet("background-color: rgb(87, 255, 171);\n"
"color: rgb(255, 255, 255);")
        self.btn7.setObjectName("btn7")
        self.btn9 = QtWidgets.QPushButton(self.centralwidget)
        self.btn9.setGeometry(QtCore.QRect(200, 70, 100, 70))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.btn9.setFont(font)
        self.btn9.setStyleSheet("background-color: rgb(87, 255, 171);\n"
"color: rgb(255, 255, 255);")
        self.btn9.setObjectName("btn9")
        self.btn_kob = QtWidgets.QPushButton(self.centralwidget)
        self.btn_kob.setGeometry(QtCore.QRect(300, 70, 100, 70))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.btn_kob.setFont(font)
        self.btn_kob.setStyleSheet("background-color: rgb(87, 255, 171);\n"
"color: rgb(255, 255, 255);")
        self.btn_kob.setObjectName("btn_kob")
        self.btn_plus = QtWidgets.QPushButton(self.centralwidget)
        self.btn_plus.setGeometry(QtCore.QRect(300, 210, 100, 70))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.btn_plus.setFont(font)
        self.btn_plus.setStyleSheet("background-color: rgb(87, 255, 171);\n"
"color: rgb(255, 255, 255);")
        self.btn_plus.setObjectName("btn_plus")
        self.btn_bol = QtWidgets.QPushButton(self.centralwidget)
        self.btn_bol.setGeometry(QtCore.QRect(300, 140, 100, 70))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.btn_bol.setFont(font)
        self.btn_bol.setStyleSheet("background-color: rgb(87, 255, 171);\n"
"color: rgb(255, 255, 255);")
        self.btn_bol.setObjectName("btn_bol")
        self.btn_minus = QtWidgets.QPushButton(self.centralwidget)
        self.btn_minus.setGeometry(QtCore.QRect(300, 280, 100, 70))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.btn_minus.setFont(font)
        self.btn_minus.setStyleSheet("background-color: rgb(87, 255, 171);\n"
"color: rgb(255, 255, 255);")
        self.btn_minus.setObjectName("btn_minus")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add()
        self.is_equal = True

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.et_number.setText(_translate("MainWindow", "0"))
        self.btn0.setText(_translate("MainWindow", "0"))
        self.btn_equal.setText(_translate("MainWindow", "="))
        self.btn1.setText(_translate("MainWindow", "1"))
        self.btn2.setText(_translate("MainWindow", "2"))
        self.btn3.setText(_translate("MainWindow", "3"))
        self.btn6.setText(_translate("MainWindow", "6"))
        self.btn4.setText(_translate("MainWindow", "4"))
        self.btn5.setText(_translate("MainWindow", "5"))
        self.btn8.setText(_translate("MainWindow", "8"))
        self.btn7.setText(_translate("MainWindow", "7"))
        self.btn9.setText(_translate("MainWindow", "9"))
        self.btn_kob.setText(_translate("MainWindow", "*"))
        self.btn_plus.setText(_translate("MainWindow", "+"))
        self.btn_bol.setText(_translate("MainWindow", "/"))
        self.btn_minus.setText(_translate("MainWindow", "-"))

    def add(self):
        self.btn0.clicked.connect(lambda:self.write_number(self.btn0.text()))
        self.btn1.clicked.connect(lambda:self.write_number(self.btn1.text()))
        self.btn2.clicked.connect(lambda:self.write_number(self.btn2.text()))
        self.btn3.clicked.connect(lambda:self.write_number(self.btn3.text()))
        self.btn4.clicked.connect(lambda:self.write_number(self.btn4.text()))
        self.btn5.clicked.connect(lambda:self.write_number(self.btn5.text()))
        self.btn6.clicked.connect(lambda:self.write_number(self.btn6.text()))
        self.btn7.clicked.connect(lambda:self.write_number(self.btn7.text()))
        self.btn8.clicked.connect(lambda:self.write_number(self.btn8.text()))
        self.btn9.clicked.connect(lambda:self.write_number(self.btn9.text()))
        self.btn_kob.clicked.connect(lambda:self.write_number(self.btn_kob.text()))
        self.btn_bol.clicked.connect(lambda:self.write_number(self.btn_bol.text()))
        self.btn_plus.clicked.connect(lambda:self.write_number(self.btn_plus.text()))
        self.btn_minus.clicked.connect(lambda:self.write_number(self.btn_minus.text()))

        self.btn_equal.clicked.connect(self.result)

    def write_number(self, number):
        if self.et_number.text() == "0" or self.is_equal:
            self.et_number.setText(number)
            self.is_equal = False
        else:
            self.et_number.setText(self.et_number.text() + number)

    def result(self):
        res = eval(self.et_number.text())
        self.et_number.setText(str(res))
        self.is_equal = True


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
